import { Command } from 'commander';
import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { join, resolve } from 'node:path';
import { ui } from '../lib/ui.js';

/**
 * `ivaronix init` — interactive project bootstrap.
 *
 * Without flags this is an OpenCode-style wizard that asks the user a few
 * targeted questions and writes a `.ivaronix/` directory tree + a tailored
 * `.env` template. With `--non-interactive` it falls back to the original
 * silent scaffold.
 */
export const initCommand = new Command('init')
  .description('Create a .ivaronix/ project folder (interactive wizard by default)')
  .option('--non-interactive', 'skip questions; write defaults only')
  .option('--force', 'overwrite an existing .ivaronix/ folder')
  .action(async (opts: { nonInteractive?: boolean; force?: boolean }) => {
    const root = join(process.cwd(), '.ivaronix');
    if (existsSync(root) && !opts.force) {
      ui.fail(`.ivaronix/ already exists at ${root}`);
      ui.hint('pass --force to overwrite, or rm -rf .ivaronix and re-run');
      process.exitCode = 1;
      return;
    }

    // Honor IVARONIX_NETWORK / OG_NETWORK env in non-interactive mode · used to
    // hardcode 'testnet' regardless of the shell-set network.
    const envNetwork = (process.env.IVARONIX_NETWORK ?? process.env.OG_NETWORK ?? '').toLowerCase();
    let answers = {
      network: (envNetwork === 'mainnet' ? 'mainnet' : 'testnet') as 'testnet' | 'mainnet',
      passportPlanned: true,
      defaultSkill: 'private-doc-review',
      writeDotEnv: false,
    };

    if (!opts.nonInteractive) {
      const rl = createInterface({ input, output });
      try {
        ui.title('ivaronix · init wizard');
        ui.hint('press enter to accept the default in [brackets]');
        ui.divider();

        const net = (await rl.question('network [testnet|mainnet] (testnet): ')).trim().toLowerCase();
        if (net === 'mainnet') answers.network = 'mainnet';

        const passport = (await rl.question('plan to mint an Agent Passport? [Y/n]: ')).trim().toLowerCase();
        if (passport === 'n' || passport === 'no') answers.passportPlanned = false;

        const skill = (await rl.question('default skill [private-doc-review]: ')).trim();
        if (skill) answers.defaultSkill = skill;

        const env = (await rl.question('also write a .env template at the repo root? [y/N]: ')).trim().toLowerCase();
        if (env === 'y' || env === 'yes') answers.writeDotEnv = true;

        ui.divider();
      } finally {
        rl.close();
      }
    }

    const dirs = [
      'policies',
      'receipts/local',
      'receipts/pending',
      'receipts/anchored',
      'skills',
      'workspaces',
      'memory/snapshots',
      'memory/burn',
      'memory/vector',
      'memory/graph/episodes',
      'memory/graph/facts',
      'snapshots',
      'worktrees',
      'swarm',
      'traces',
      'kv-cache',
      'conversations',
    ];
    for (const d of dirs) mkdirSync(join(root, d), { recursive: true });

    writeFileSync(
      join(root, 'config.json'),
      JSON.stringify(
        {
          network: answers.network,
          daemonPort: 8787,
          defaultSkill: answers.defaultSkill,
          generatedAt: new Date().toISOString(),
        },
        null,
        2,
      ),
    );
    writeFileSync(
      join(root, 'AGENT.md'),
      `# Agent\n\n${answers.passportPlanned
        ? '_passport summary will appear here once minted via `ivaronix passport mint`_\n'
        : '_no passport planned for this project_\n'}`,
    );
    writeFileSync(join(root, 'CONTEXT.md'), '# Context\n\nDescribe the current scope.\n');
    writeFileSync(join(root, 'todo.md'), '# Todo\n\n- [ ] First task\n');
    writeFileSync(join(root, 'notes.md'), '# Notes\n\nWorking notes go here.\n');
    writeFileSync(
      join(root, 'hooks.yml'),
      `# Lifecycle hooks (claude-mem pattern)
PreToolUse:
  - match: "wallet.*"
    run: "ivaronix safety-check wallet"
PostToolUse:
  - match: "shell|file_write|skill_exec"
    run: "ivaronix observation extract"
SessionEnd:
  - run: "ivaronix memory consolidate"
PreCompact:
  - run: "ivaronix memory snapshot --upload"
`,
    );

    if (answers.writeDotEnv) {
      const envPath = resolve(process.cwd(), '.env');
      if (!existsSync(envPath) || opts.force) {
        writeFileSync(
          envPath,
          `# Ivaronix .env (generated by \`ivaronix init\`)
# Canonical IVARONIX_* names per packages/runtime/src/env.ts.
# Legacy aliases (OG_*, EVM_*, ZG_*) still resolve via the alias chain
# but print a one-time deprecation warning per alias used.
IVARONIX_NETWORK=${answers.network}
IVARONIX_SIGNER_KEY=
IVARONIX_WALLET_ADDRESS=
IVARONIX_ROUTER_KEY=
IVARONIX_ROUTER_URL=
IVARONIX_ROUTER_PROVIDER=
IVARONIX_DEFAULT_MODEL=0GM-1.0-35B-A3B
`,
        );
        ui.pass(`.env template written to ${envPath}`);
        ui.hint('fill in IVARONIX_SIGNER_KEY, IVARONIX_ROUTER_KEY, etc. before running `ivaronix doctor`');
      } else {
        ui.info('.env already exists — left untouched');
      }
    }

    ui.divider();
    ui.banner(true, `→ .ivaronix/ initialized for ${answers.network}`);
    ui.hint('Next: `ivaronix doctor --network` then `ivaronix passport mint` then `ivaronix doc ask`');
  });
