import { OUTFIT_SEMIBOLD_B64 } from './fonts/Outfit-SemiBold.b64';

/**
 * Bundled brand font for `next/og`'s `ImageResponse`.
 *
 * Why inline base64, not bundled .ttf:
 *
 * satori (inside `next/og`) parses TTF / OTF / WOFF — not WOFF2 — and
 * `ImageResponse` has no usable default font in the Vercel function
 * bundle, so `fonts: []` / `undefined` throws "No fonts are loaded."
 * Fetching from fonts.googleapis.com at request time was both
 * format-fragile (browser UAs get .woff2) and a request-time network
 * dependency.
 *
 * The vendored-.ttf-via-URL approach (`new URL('./fonts/Outfit-SemiBold.ttf',
 * import.meta.url)` + `fileURLToPath(url.href)` + `readFile(path)`) worked
 * in `next dev` and local `next build` but failed on Vercel runtime with
 * `ERR_INVALID_ARG_TYPE` from `fileURLToPath`. Webpack's URL-asset rewrite
 * hands back a `URL` instance from a different module realm than the one
 * `node:url`'s native `instanceof` check expects, and even passing
 * `url.href` (the string form) didn't fix the underlying tracing gap.
 *
 * The fix here (USER_TODO §B-V2-2 · ✅ SHIPPED) is to inline the TTF as
 * a base64 string in a sibling module (auto-generated by
 * `scripts/diag/regenerate-og-font-b64.ts`) and decode it to a Buffer
 * at module-init. No filesystem read, no URL resolution, no module-realm
 * gotchas — guaranteed to work on every runtime that has `Buffer`.
 *
 * Note: the font-path hardening (this file) was necessary but not
 * sufficient. The route 500 also required removing the satori-
 * unsupported `<text>` element inside the brand-mark SVG — see commit
 * 3fbb570 for the path-only italic-i replacement.
 *
 * Cost: ~65 KB of base64 in the serverless bundle. Trivial compared to
 * the ML weights we *exclude* from tracing in `next.config.ts`.
 *
 * Returns `[]` if the decode ever fails (truncated or corrupted b64) —
 * callers must treat empty as "render something other than an
 * ImageResponse" (a bare 503), since satori can't lay out text with
 * zero fonts. In practice this branch is dead — `Buffer.from(b64,
 * 'base64')` doesn't throw on bad input, it just produces shorter
 * output. We still gate on `byteLength > 0` defensively.
 */
export type OgFont = { name: string; data: ArrayBuffer; style: 'normal'; weight: 600 };

let cached: ArrayBuffer | null = null;

function decodeOnce(): ArrayBuffer | null {
  if (cached) return cached;
  try {
    const buf = Buffer.from(OUTFIT_SEMIBOLD_B64, 'base64');
    if (buf.byteLength === 0) return null;
    // Allocate a fresh standalone ArrayBuffer and copy the bytes in. This
    // sidesteps two runtime gotchas: (1) `buf.buffer` is the underlying
    // backing buffer which may be a pooled / shared region (Node's small-
    // allocation pool re-uses one big ArrayBuffer across many Buffers); we
    // don't want satori to receive bytes outside the Buffer's bounds.
    // (2) On some Vercel function runtimes the Buffer is SharedArrayBuffer-
    // backed and satori's `instanceof ArrayBuffer` check rejects it. The
    // copy is ~50 KB; the cost is negligible compared to the OG-image
    // render itself.
    const ab = new ArrayBuffer(buf.byteLength);
    new Uint8Array(ab).set(buf);
    cached = ab;
    return cached;
  } catch {
    return null;
  }
}

export async function loadBrandFont(): Promise<OgFont[]> {
  const data = decodeOnce();
  if (!data) return [];
  return [{ name: 'Outfit', data, style: 'normal', weight: 600 }];
}
