// CLAUDE.md section 10 regression: brand-token drift lint.
//
// Closes USER_TODO B-V2-9 (pnpm brand:check). The canonical palette
// lives in brand/tokens.json; any hex color in apps/studio/src that
// is not a member of that palette is drift, by definition. Without
// this gate, ad-hoc Tailwind arbitrary-color literals like
// bg-[#fafafa] silently bypass the brand contract and the Studio
// renders look "less designed" per CLAUDE.md section 10.
//
// Scope (per the B-V2-9 spec):
//   apps/studio/src/**/*.{ts,tsx,css}
//
// Only hash-prefixed hex values (CSS color syntax) are flagged.
// 0x-prefixed strings (addresses, hashes, signatures) are ignored
// because the matcher requires the # prefix.
//
// Allow-list exception marker (inline, on the same line):
//   brand-check:allow:short-reason
// Use sparingly. Every exception is a footgun.
//
// Amnesty list (cron-sweep finding 2026-05-10): the regression
// SHIPS with existing drift documented. The point is to gate NEW
// drift, not to force a multi-file color refactor in one commit.
// Each amnesty entry is a (file, line, hex) tuple. If the line at
// that file/line no longer contains that hex (e.g. someone refactored
// it), the amnesty entry is silently dropped on the next run. If
// someone adds a NEW hex outside the canonical palette anywhere, it
// fails. Cleanup tracked in USER_TODO B-V2-BRAND-AMNESTY.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..');
const STUDIO_SRC = resolve(REPO_ROOT, 'apps', 'studio', 'src');
const TOKENS_PATH = resolve(REPO_ROOT, 'brand', 'tokens.json');

let asserts = 0;
const fail = (msg: string): never => {
  console.error(`FAIL: ${msg}`);
  process.exit(1);
};
const ok = (label: string) => {
  asserts++;
  console.log(`OK: ${label}`);
};

// ─── Step 1: extract canonical palette ─────────────────────────────────
function extractHexLiterals(value: unknown, out: Set<string>): void {
  if (typeof value === 'string') {
    for (const m of value.matchAll(/#([0-9A-Fa-f]{3,8})\b/g)) {
      out.add(m[0].toUpperCase());
    }
  } else if (Array.isArray(value)) {
    for (const v of value) extractHexLiterals(v, out);
  } else if (value !== null && typeof value === 'object') {
    for (const v of Object.values(value)) extractHexLiterals(v, out);
  }
}

// Normalize all hex shapes to 6-char uppercase (e.g. "#fff" → "#FFFFFF").
// 3-char shorthand: each digit doubles. 4-char (with alpha): same shape.
// 8-char (with alpha): strip the trailing 2 alpha digits to compare core
// color; CSS allows alpha but the brand palette only declares 6-char
// values today. If alpha-aware comparison is ever required, extend this.
function normalizeHex(hex: string): string {
  const body = hex.replace(/^#/, '').toUpperCase();
  if (body.length === 3) {
    return '#' + body.split('').map((c) => c + c).join('');
  }
  if (body.length === 4) {
    // RGBA shorthand → expand to 8-char then strip alpha
    return '#' + body.slice(0, 3).split('').map((c) => c + c).join('');
  }
  if (body.length === 8) {
    return '#' + body.slice(0, 6);
  }
  return '#' + body;
}

const tokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf8'));
const rawCanonical = new Set<string>();
extractHexLiterals(tokens, rawCanonical);
const canonical = new Set<string>();
for (const c of rawCanonical) canonical.add(normalizeHex(c));
ok(`extracted ${canonical.size} unique canonical hex colors from brand/tokens.json`);

// ─── Step 2: walk apps/studio/src ──────────────────────────────────────
function listFiles(dir: string, exts: string[]): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = resolve(dir, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...listFiles(path, exts));
    } else if (exts.some((e) => entry.endsWith(e))) {
      out.push(path);
    }
  }
  return out;
}

const sourceFiles = listFiles(STUDIO_SRC, ['.ts', '.tsx', '.css']);
ok(`scanning ${sourceFiles.length} files under apps/studio/src/`);

// ─── Step 3: find drift ────────────────────────────────────────────────
interface Violation {
  file: string;
  line: number;
  hex: string;
  context: string;
}

// Amnesty list: hex literals that existed when the regression first
// shipped. New hits outside this list fail the build.
//
// Snapshot file: scripts/qa/metamask-e2e/brand-amnesty.json
//   Format: array of "file:line:hex" tuples (string array).
//   Generated by running `pnpm tsx verify-brand-token-drift.ts --update-amnesty`.
//   Cleanup tracked in USER_TODO §B-V2-BRAND-AMNESTY.
//
// Why a snapshot file rather than inline:
//   - 100+ existing entries don't fit cleanly in a TS literal
//   - The JSON makes it trivial to regenerate after a bulk cleanup
//   - Diffs of brand-amnesty.json show "X new exceptions added" vs
//     "X cleaned up" at PR-review time
const AMNESTY_PATH = resolve(HERE, 'brand-amnesty.json');
let AMNESTY: ReadonlySet<string>;
try {
  const json = JSON.parse(readFileSync(AMNESTY_PATH, 'utf8')) as string[];
  AMNESTY = new Set(json);
  ok(`loaded ${AMNESTY.size} amnesty entries from brand-amnesty.json`);
} catch {
  AMNESTY = new Set();
  ok('no brand-amnesty.json found · running with empty amnesty list');
}

const updateAmnesty = process.argv.includes('--update-amnesty');

const violations: Violation[] = [];

// Hex-color regex: `#` followed by 3, 4, 6, or 8 hex digits, with a
// non-hex boundary on each side so we don't pick up parts of longer
// hex strings (e.g. `#abcdef0123456789` would not match because the
// trailing 7 chars push the match past the 6/8-digit alternates).
//
// Word boundary `\b` doesn't work cleanly with `#` (which is a
// non-word char), so we anchor on a non-hex char (or string-start)
// before `#` and a non-hex char (or string-end) after.
const HEX_RE = /(^|[^0-9A-Fa-f])(#[0-9A-Fa-f]{3,8})(?![0-9A-Fa-f])/g;

for (const file of sourceFiles) {
  const lines = readFileSync(file, 'utf8').split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    // Inline allow-list marker: skip this line entirely.
    if (line.includes('brand-check:allow:')) continue;
    // Skip pure comment lines (// or *).
    const trimmed = line.trimStart();
    if (trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
    HEX_RE.lastIndex = 0;
    for (const m of line.matchAll(HEX_RE)) {
      const hex = m[2]!;
      // Filter: must be a plausible CSS hex color shape (3, 4, 6, 8 digits).
      const body = hex.length - 1;
      if (body !== 3 && body !== 4 && body !== 6 && body !== 8) continue;
      // Sweep 77: skip 4-char purely-numeric (`#1004`, `#9999`) — these
      // are receipt IDs ("See receipt #1004") or issue numbers, never
      // valid CSS shorthand in this codebase. Letter-containing 4-chars
      // (`#FF00`) stay flagged.
      if (body === 4 && /^#\d{4}$/.test(hex)) continue;
      const normalized = normalizeHex(hex);
      if (canonical.has(normalized)) continue;
      const relPath = relative(REPO_ROOT, file).replace(/\\/g, '/');
      const amnestyKey = `${relPath}:${i + 1}:${hex}`;
      if (AMNESTY.has(amnestyKey)) continue;
      violations.push({
        file: relPath,
        line: i + 1,
        hex,
        context: line.trim().slice(0, 120),
      });
    }
  }
}

if (updateAmnesty) {
  // Write the union of the existing amnesty + any new violations.
  // BUG FIX (sweep 60): the previous version overwrote the amnesty
  // with NEW violations only (the `violations` array, populated only
  // when a hit is NOT in AMNESTY). Running --update against a clean
  // codebase would have discarded every existing entry. The
  // RIGHT behavior is union: old amnesty entries that no longer
  // match (e.g. line numbers shifted by an edit) drop OUT (because
  // they're not in the current violation set), while NEW violations
  // get added IN.
  //
  // Approach: walk all source files again and capture EVERY hit
  // (in-amnesty + new) as the new amnesty. The amnesty is then a
  // snapshot of the current state, not a delta.
  const allHits = new Set<string>(AMNESTY); // start with old amnesty
  // Re-walk to capture hits that were in AMNESTY (skipped above) too.
  for (const file of sourceFiles) {
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      if (line.includes('brand-check:allow:')) continue;
      const trimmed = line.trimStart();
      if (trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
      HEX_RE.lastIndex = 0;
      for (const m of line.matchAll(HEX_RE)) {
        const hex = m[2]!;
        const body = hex.length - 1;
        if (body !== 3 && body !== 4 && body !== 6 && body !== 8) continue;
        if (body === 4 && /^#\d{4}$/.test(hex)) continue;
        const normalized = normalizeHex(hex);
        if (canonical.has(normalized)) continue;
        const relPath = relative(REPO_ROOT, file).replace(/\\/g, '/');
        allHits.add(`${relPath}:${i + 1}:${hex}`);
      }
    }
  }
  // Drop stale entries: anything in old AMNESTY but no longer
  // matching current line content. We do this by intersecting:
  // keep only entries that are also in the current sweep result.
  const currentSweep = new Set<string>();
  for (const file of sourceFiles) {
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      const trimmed = line.trimStart();
      if (trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
      HEX_RE.lastIndex = 0;
      for (const m of line.matchAll(HEX_RE)) {
        const hex = m[2]!;
        const body = hex.length - 1;
        if (body !== 3 && body !== 4 && body !== 6 && body !== 8) continue;
        if (body === 4 && /^#\d{4}$/.test(hex)) continue;
        const normalized = normalizeHex(hex);
        if (canonical.has(normalized)) continue;
        const relPath = relative(REPO_ROOT, file).replace(/\\/g, '/');
        currentSweep.add(`${relPath}:${i + 1}:${hex}`);
      }
    }
  }
  const finalAmnesty = Array.from(allHits).filter((entry) => currentSweep.has(entry)).sort();
  const out = JSON.stringify(finalAmnesty, null, 2) + '\n';
  writeFileSync(AMNESTY_PATH, out);
  console.log(`updated brand-amnesty.json: ${finalAmnesty.length} entries (was ${AMNESTY.size}, +${finalAmnesty.length - [...AMNESTY].filter((e) => currentSweep.has(e)).length} new, -${AMNESTY.size - [...AMNESTY].filter((e) => currentSweep.has(e)).length} stale)`);
  process.exit(0);
}

if (violations.length > 0) {
  console.error(`\nFAIL: ${violations.length} hex literal(s) NOT in brand/tokens.json AND NOT in amnesty:`);
  for (const v of violations) {
    console.error(`  ${v.file}:${v.line} · ${v.hex}`);
    console.error(`    ${v.context}`);
  }
  console.error('');
  console.error('Resolution options:');
  console.error('  1. Replace the hex with a brand token (CSS var or Tailwind utility)');
  console.error('  2. Add the color to brand/tokens.json + brand/tokens.css if it');
  console.error('     genuinely belongs in the canonical palette (rare)');
  console.error('  3. Add `// brand-check:allow:<reason>` on the line for an');
  console.error('     intentional, documented exception (use sparingly)');
  console.error('  4. Run `pnpm tsx verify-brand-token-drift.ts --update-amnesty`');
  console.error('     to add the current violation set to brand-amnesty.json (use');
  console.error('     this AFTER a bulk cleanup that legitimately changed which');
  console.error('     hexes appear; commits with new amnesty entries should explain');
  console.error('     why each new exception is intentional)');
  process.exit(1);
}

ok(`no hex-color drift across ${sourceFiles.length} studio source files`);
console.log(`\n${asserts}/${asserts} assertions passed`);
process.exit(0);
