/**
 * 2-wallet test infrastructure setup (iter-132).
 *
 * Generates or loads Wallet B (the grantee/reader/non-operator
 * counterparty for 2-wallet flows). Funds it from operator if its
 * balance is below the minimum gas threshold.
 *
 * Wallet B is loaded from .ivaronix/test-wallets/wallet-b.json
 * (gitignored). If the file doesn't exist, a fresh deterministic
 * wallet is generated from a fixed seed so subsequent runs recover
 * the same address (idempotent funding + grant tests).
 *
 * Reads from .env: IVARONIX_SIGNER_KEY (or legacy EVM_PRIVATE_KEY),
 * IVARONIX_RPC_URL (or legacy OG_RPC_URL).
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Wallet, JsonRpcProvider, formatEther, parseEther } from 'ethers';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..');
const FIXTURE = resolve(REPO_ROOT, '.ivaronix', 'test-wallets', 'wallet-b.json');
const SEED = '0xb0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0';
const MIN_BALANCE_OG = '0.005';
const FUND_AMOUNT_OG = '0.01';

interface WalletFixture {
  address: string;
  privateKey: string;
  role: string;
}

function loadEnv(): { operatorKey: string; rpcUrl: string; chainId: number } {
  const envPath = resolve(REPO_ROOT, '.env');
  if (!existsSync(envPath)) throw new Error('.env not found at repo root');
  const env = Object.fromEntries(
    readFileSync(envPath, 'utf8')
      .split('\n')
      .filter((l) => l.includes('=') && !l.trim().startsWith('#'))
      .map((l) => {
        const idx = l.indexOf('=');
        return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()] as [string, string];
      }),
  );
  const operatorKey = env.IVARONIX_SIGNER_KEY ?? env.OG_PRIVATE_KEY ?? env.EVM_PRIVATE_KEY;
  const rpcUrl = env.IVARONIX_RPC_URL ?? env.OG_RPC_URL ?? 'https://evmrpc-testnet.0g.ai';
  if (!operatorKey) throw new Error('no operator key in .env (IVARONIX_SIGNER_KEY or EVM_PRIVATE_KEY)');
  return { operatorKey, rpcUrl, chainId: 16602 };
}

async function main(): Promise<void> {
  const { operatorKey, rpcUrl, chainId } = loadEnv();
  const provider = new JsonRpcProvider(rpcUrl, { chainId, name: 'testnet' });
  const operator = new Wallet(operatorKey, provider);

  let fixture: WalletFixture;
  if (existsSync(FIXTURE)) {
    const raw = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Record<string, unknown>;
    fixture = {
      address: raw.address as string,
      privateKey: raw.privateKey as string,
      role: (raw.role as string) ?? 'Wallet B (grantee/reader)',
    };
    console.log(`[setup-wallets] loaded Wallet B from fixture: ${fixture.address}`);
  } else {
    const fresh = new Wallet(SEED);
    fixture = {
      address: fresh.address,
      privateKey: SEED,
      role: 'Wallet B (grantee/reader/non-operator counterparty)',
    };
    mkdirSync(dirname(FIXTURE), { recursive: true });
    writeFileSync(
      FIXTURE,
      JSON.stringify(
        {
          _: 'Wallet B test fixture · gitignored · generated by scripts/qa/multi-wallet/setup-wallets.ts',
          role: fixture.role,
          address: fixture.address,
          privateKey: fixture.privateKey,
          seed: 'deterministic-iter132',
        },
        null,
        2,
      ),
    );
    console.log(`[setup-wallets] generated Wallet B: ${fixture.address}`);
  }

  const balB = await provider.getBalance(fixture.address);
  console.log(`[setup-wallets] Wallet B balance: ${formatEther(balB)} OG`);

  if (balB < parseEther(MIN_BALANCE_OG)) {
    console.log(`[setup-wallets] funding Wallet B with ${FUND_AMOUNT_OG} OG...`);
    const tx = await operator.sendTransaction({
      to: fixture.address,
      value: parseEther(FUND_AMOUNT_OG),
      gasLimit: 21000,
    });
    console.log(`[setup-wallets] fund tx: ${tx.hash}`);
    const rec = await tx.wait();
    console.log(`[setup-wallets] mined in block: ${rec?.blockNumber}`);
    const newBal = await provider.getBalance(fixture.address);
    console.log(`[setup-wallets] Wallet B post-fund balance: ${formatEther(newBal)} OG`);
  } else {
    console.log(`[setup-wallets] Wallet B already funded (>= ${MIN_BALANCE_OG} OG)`);
  }

  console.log(`\n[setup-wallets] ready · operator=${operator.address} · walletB=${fixture.address}`);
}

main().catch((e) => {
  console.error(`[setup-wallets] FAIL: ${(e as Error).message}`);
  process.exit(1);
});
